### ISSUE TITLE
Revamp Rails howto to cover local setup rather than starting a new project

### ISSUE THREAD

**Issue by daguar** [codeforamerica/howto#27]

**Comment by daguar** [comment]
cc @alexsoble if you wanna help out

**Comment by alexsoble** [comment]
@daguar That I do!

**Comment by migurski** [comment]
:+1:

I’d like to reduce the amount of content [aimed at setting up a new Rails application](https://github.com/codeforamerica/howto/blob/master/Rails.md#recommended-configuration), and instead target this guide toward people attempting to run existing Rails applications.

**Comment by daguar** [comment]
:+1: to that @migurski.

**Comment by monfresh** [comment]
For configurations related to deployment on Heroku, I would recommend simply linking to Heroku's documentation instead of reinventing the wheel or unintentionally providing incorrect or outdated information.

The discussion on Slack was not entirely accurate. It is perfectly fine to precompile assets locally before pushing to Heroku. You just have to make sure to specify the production environment when you run the rake task. See these articles for more details:

https://devcenter.heroku.com/articles/rails-asset-pipeline
https://devcenter.heroku.com/articles/getting-started-with-rails4

**Comment by migurski** [comment]
Definitely agreed, Moncef, thanks. The key to these guides is to briefly summarize external documentation so it’s clear which way we’re endorsing and building against.

**Comment by monfresh** [comment]
:+1: I'm planning on linking to these how-tos for some 18F repos.

**Comment by migurski** [comment]
Been a few months, any movement here? The Rails guide is still not [what we’d want](#issuecomment-70306837) out of a howto.

**Comment by monfresh** [comment]
If the goal is to show people how to run existing Rails applications, then you don't really need a guide at all. What is needed to run any particular Rails app will depend on the app, and that should be covered in the app's Readme.

Ruby is one of the prerequisites, and there is already a guide for that, as well as one for command line tools, Homebrew, and RVM. The rest will depend on what other tools the app depends on, such as the type of DB, and any other things that need to be installed. The app-specific setup should be scripted as much as possible so that the user only needs to run one command to set everything up. Rails 4.2 now comes with a [`bin/setup` script](https://github.com/rails/rails/pull/15189) where you can define everything that needs to happen to configure the app.

**Comment by daguar** [comment]
I renamed this to "Revamp Rails howto to cover local setup rather than starting a new project" based on the converstaion.

**Comment by daguar** [comment]
> What is needed to run any particular Rails app will depend on the app, and that should be covered in the app's Readme.

I do think you're right about this — surveying a bunch of Rails apps on CfA's account, many have specific system dependency installs (eg, Solr) and/or specific rake tasks that need to be run (eg, `rake import:whatever`).

That said:

1. There are a few common bits that most Rails apps need, as well as some basic explanation of the working parts that might need customization to your local environment (particularly the database setup) where a quick howto might be useful.
2. The existing Rails.md file isn't very helpful for local setup anyway, so we should at least move/remove that content.

I'm taking a quick stab at this right now, PR coming.
